// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWCGnFSEqHwDVgre2Jd73A8eVkSnRczCQ',
    appId: '1:558757635295:web:94b84faed8e41f5970f56a',
    messagingSenderId: '558757635295',
    projectId: 'sca-translator-app',
    authDomain: 'sca-translator-app.firebaseapp.com',
    storageBucket: 'sca-translator-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEVZdtBAEMd5tHkpqJL6xvkw3z1MNhcPE',
    appId: '1:558757635295:android:02bb8d670a2ec00170f56a',
    messagingSenderId: '558757635295',
    projectId: 'sca-translator-app',
    storageBucket: 'sca-translator-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChqg_TvmKnkQmr2lFKJfnRNh9UqPzQmjI',
    appId: '1:558757635295:ios:5405c2718fc7320f70f56a',
    messagingSenderId: '558757635295',
    projectId: 'sca-translator-app',
    storageBucket: 'sca-translator-app.firebasestorage.app',
    iosBundleId: 'com.sca.scaTranslatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChqg_TvmKnkQmr2lFKJfnRNh9UqPzQmjI',
    appId: '1:558757635295:ios:5405c2718fc7320f70f56a',
    messagingSenderId: '558757635295',
    projectId: 'sca-translator-app',
    storageBucket: 'sca-translator-app.firebasestorage.app',
    iosBundleId: 'com.sca.scaTranslatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWCGnFSEqHwDVgre2Jd73A8eVkSnRczCQ',
    appId: '1:558757635295:web:eba02c0eed7455cf70f56a',
    messagingSenderId: '558757635295',
    projectId: 'sca-translator-app',
    authDomain: 'sca-translator-app.firebaseapp.com',
    storageBucket: 'sca-translator-app.firebasestorage.app',
  );
}
